#!/bin/bash
set -x

aws ecr get-login-password --region ap-northeast-1 | \
docker login --username AWS --password-stdin 165463520094.dkr.ecr.ap-northeast-1.amazonaws.com
aws sts get-caller-identity


